### ISSUE TITLE
only length-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by rangeardt** [HenrYxZ/object-classification#2]
Hello, first of all i don't have the train_auto function, i am on ubuntu 16 .04 LTS , i try different installation, manually install opencv 2/3 with contrib, i try installling using pip

what opencv version do you run ?
I have to change all the path like replace cv2.SVM with cv2.ml.SVM..., replace svm.ORB by svm.ORB_create() 

Secondly, ( i have to replace train_auto, by train) i got this error when i reach the svm part on the train call   : TypeError: only length-1 arrays can be converted to Python scalars
Any Idea?

**Comment by drewbitt** [comment]
just regular ORB (not ORB_create() ) cv2.SVM as well as train_auto are in OpenCV 2. Working on my OpenCV version 2.4 with Python version 2.7.
